mh_cms_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: MhCmsBundle:Default:index }

MhCmsBundle_websites:
    resource: "@MhCmsBundle/Resources/config/routing/website.yml"
    prefix:   /websites
    
MhCmsBundle_pages:
    resource: "@MhCmsBundle/Resources/config/routing/page.yml"
    prefix:   /pages
    
MhCmsBundle_content_blocks:
    resource: "@MhCmsBundle/Resources/config/routing/contentblock.yml"
    prefix:   /content_blocks
    
MhCmsBundle_content_block_types:
    resource: "@MhCmsBundle/Resources/config/routing/contentblocktype.yml"
    prefix:   /content_block_types
    
MhCmsBundle_content_block_templates:
    resource: "@MhCmsBundle/Resources/config/routing/contentblocktemplate.yml"
    prefix:   /content_block_templates