parameters:
#    mh_cms.example.class: Mh\CmsBundle\Example

services:
#    mh_cms.example:
#        class: %mh_cms.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

  website_allocation_handler:
      class: Mh\CmsBundle\Classes\Website\AllocationHandler
      arguments: [@security.context, @doctrine.orm.entity_manager]
