content_block_templates:
    pattern:  /
    defaults: { _controller: "MhCmsBundle:ContentBlockTemplate:index" }

content_block_templates_show:
    pattern:  /{id}/show
    defaults: { _controller: "MhCmsBundle:ContentBlockTemplate:show" }

content_block_templates_new:
    pattern:  /new
    defaults: { _controller: "MhCmsBundle:ContentBlockTemplate:new" }

content_block_templates_create:
    pattern:  /create
    defaults: { _controller: "MhCmsBundle:ContentBlockTemplate:create" }
    requirements: { _method: post }

content_block_templates_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "MhCmsBundle:ContentBlockTemplate:edit" }

content_block_templates_update:
    pattern:  /{id}/update
    defaults: { _controller: "MhCmsBundle:ContentBlockTemplate:update" }
    requirements: { _method: post }

content_block_templates_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "MhCmsBundle:ContentBlockTemplate:delete" }
    requirements: { _method: post }
