pages:
    pattern:  /
    defaults: { _controller: "MhCmsBundle:Page:index" }

pages_show:
    pattern:  /{id}/show
    defaults: { _controller: "MhCmsBundle:Page:show" }

pages_new:
    pattern:  /new
    defaults: { _controller: "MhCmsBundle:Page:new" }

pages_create:
    pattern:  /create
    defaults: { _controller: "MhCmsBundle:Page:create" }
    requirements: { _method: post }

pages_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "MhCmsBundle:Page:edit" }
    
pages_stage:
    pattern:  /{pageId}/stage
    defaults: { _controller: "MhCmsBundle:Page:stage" }

pages_update:
    pattern:  /{id}/update
    defaults: { _controller: "MhCmsBundle:Page:update" }
    requirements: { _method: post }

pages_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "MhCmsBundle:Page:delete" }
    requirements: { _method: post }

pages_add_block:
    pattern: /{pageId}/add_block
    defaults: { _controller: "MhCmsBundle:Page:addBlock" }
    
pages_remove_sub_block:
    pattern: /{pageId}/remove_sub_block
    defaults: { _controller: "MhCmsBundle:Page:removeSubBlock" }